### ISSUE TITLE
Overlay.DateTime

### ISSUE THREAD

**Issue by daimashangchuan** [caoyongfeng0214/rn-overlay#2]
你好   使用  DateTime   遇到的问题

const title = props.title || '';
  const value = props.value || '';
  const placeholder = props.placeholder || '';
  const mode = props.mode || 'YMDhm'; //  YM  YMD YMDh YMDhm YMDhms hm hms
  const closeText = props.closeText || '取消';
  const confirmText = props.confirmText || '确定';
  const onConfirm = props.onConfirm || null;  // 点击确定按钮事件
  const format = props.format || 'YYYY-MM-DD HH:mm';

const newValue = value? JSON.parse(JSON.stringify(value)): '';
  newValue&&newValue.splice(1,1, newValue[1]-1)

<DateTime
        mode={mode}
        value={value || [-1, -1, -1]}
        closeText={closeText}
        confirmText={confirmText}
        // min={min}
        // max={max}
        min={{Y:2022, M:1, D:1, h: 0, m: 0, s: 0}}
        max={{Y:2022, M:12, D:31, h: 23, m: 59, s: 59}}
        input={
          <Text style={[styles.OverlayText, styles.textRight]}>
            {newValue ? moment(newValue).format(format) : placeholder} &nbsp;
            <AntDesign name='right' size={14} />
          </Text>
        }
        onConfirm={(vals) => {
          onConfirm && onConfirm(vals)
        }}
      />

滑动月份的时候报这个错误了

Invariant Violation: [1163,{"type":"value","value":"<<NaN>>","offset":0}] is not usable as a native method argument
This error is located at:
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (at picker.js:445)

请问一下   有没有解决的方法

**Comment by caoyongfeng0214** [comment]
请提供尽量简洁和清晰的代码。
