### ISSUE TITLE
Picker这个组件onConfirm事件返回的值有误

### ISSUE THREAD

**Issue by HHZWill** [caoyongfeng0214/rn-overlay#5]
`onConfirm={(selectedVal, selectedIdx, selectedItem) => {
  console.log(selectedVal, selectedIdx, selectedItem);
}}`
选择第一个选项时，打印出来的值为：
`undefined  [0]  undefined`

**Comment by caoyongfeng0214** [comment]
感谢反馈。等验证之后处理。

**Comment by caoyongfeng0214** [comment]
@HHZWill  未复现你指出的问题。请提供更多信息。
